### ISSUE TITLE
Einstellungsbutton zum Main-Menu hinzufügen

### ISSUE THREAD

**Issue by ajfdik** [BogyMitutoyoCTL/BOGY-App-2024-03#11]
Es wird ein Button im Mainmenu benötigt, damit man zum Einstellungs Menu kommt.

**Comment by stauseepokal** [comment]
Finished
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/b5c7db98-53d5-4059-a6ce-5e8e0c415abb)
