### ISSUE TITLE
Zu lange Zahlen bei "Aktuelle Daten anzeigen

### ISSUE THREAD

**Issue by ajfdik** [BogyMitutoyoCTL/BOGY-App-2024-03#17]
![Screenshot_20240319_155413](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/158302750/1066530f-611b-4b80-bf34-0b704f05fb2e)

**Comment by stauseepokal** [comment]
Done
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/0d0b65b0-ecd5-480f-8e73-5b1fed3f7a1b)
