### ISSUE TITLE
Implement Current Values dialog

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2024-03#2]

**Comment by stauseepokal** [comment]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/c0ca807e-abe1-4af1-b862-544014a55d45)

**Comment by stauseepokal** [comment]
Finished: 
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/7f57327e-352a-4b15-9c10-50d0354d4e23)

Now only edit the datas with the real values
