### ISSUE TITLE
Translate title of time synchronization

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2024-03#23]
English:
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/25632350/4b9daed9-6398-48db-b8f2-e280882c3538)

**Comment by stauseepokal** [comment]
Done
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/e8347c4f-b54b-4396-af80-f88cfb5a152e)
