### ISSUE TITLE
About us does not look nice

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2024-03#25]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/25632350/671049cd-96e3-4a12-86f3-9c3784af536b)

We can perhaps fix the overflow by adding a scrollbar.

The Mitutoyo Logo does not look nice with the black background. Here's an official version of the Mitutoyo Logo. Using the single M is prohibited.

![Mitutoyo Logo vec](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/25632350/8f5b2e7e-8c21-4535-b6c1-2604d56fe923)

**Comment by ajfdik** [comment]
Bild wurde geändert, ich arbeite nun an der Scrollbar...

**Comment by ajfdik** [comment]
Ich habe nun eine scrollbar hinzugefügt, kann diese aber nicht testen, da es bei mir kein overflow gibt...
