### ISSUE TITLE
Implement Time Synchronization dialog

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2024-03#3]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/25632350/2fa602c0-2754-42c3-9027-2524191de2af)

**Comment by stauseepokal** [comment]
Finished. it also includes auto reload to reload the current time
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/e92e2248-4105-4dcd-bb73-8e9fba9b2512)
