### ISSUE TITLE
Abstimmung

### ISSUE THREAD

**Issue by ajfdik** [BogyMitutoyoCTL/BOGY-App-2024-03#36]
Bisher sind die Einheitenauswahl, Sprachenauswahl und Themeauswahl auf eigenen "Seiten" auf die man von der "Einstellungsseite" über ElevatedButtons erreicht. Nun hab ich die RadioListeTiles in den jeweiligen Seiten mit Dropdown lists ersetzt, was die seiten nun leer erscheinen lässt.
Die Frage ist jetzt, soll es so bleiben, wie es ist und ggf eif. gefüllt werden mit mehr Einstllmöglichkeiten wenn möglich oder sollen die Dropdowns direkt in die Einstellungsseite eingbaut werden, was zu weniger extra "Seiten" führt
schreibe 1 wenn es so bleiben soll und 2 wenn es geändert werden soll und 3 wenn du eine neue Idee hast...
Thx

**Comment by thomasw-mitutoyo-ctl** [comment]
2

Ich finde eine eigene Seite nur für einen DropDropDownButton auch zu leer. Ich würde die DropDownButtons auf die Settings-Seite übernehmen. Weniger Seiten macht es übersichtlicher für den Benutzer.

**Comment by ajfdik** [comment]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/158302750/6c3161ce-8c93-47a3-9641-b2ce11ea14d9)

**Comment by ajfdik** [comment]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/158302750/d3305844-6610-4ad9-bd2b-a6641b5a369f)
