### ISSUE TITLE
Overflow at Main Menu and Splash Screen

### ISSUE THREAD

**Issue by StrgV** [BogyMitutoyoCTL/BOGY-App-2024-03#39]
Device: Nexus 5 (Screen resolution: 1080x1920)
![Screenshot_20240320-142520](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/52709798/4ae167f0-dbba-4241-803c-ab20d68eee2d)

**Comment by ajfdik** [comment]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/158302750/9a328e59-2041-4dd3-829d-6903bac81dc2)

**Comment by ajfdik** [comment]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/158302750/6ab91a8d-57d4-4ba7-9fce-ad527be52037)

**Comment by ajfdik** [comment]
Fixed
