### ISSUE TITLE
Implement Statistics dialog

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2024-03#4]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/25632350/c14199da-9a2c-4cce-ac6e-bc6e65f2f366)

**Comment by stauseepokal** [comment]
Finished
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/2e1e3a53-c4f3-499d-a18e-1bcec920b490)
