### ISSUE TITLE
Löschen von Alarmen

### ISSUE THREAD

**Issue by ajfdik** [BogyMitutoyoCTL/BOGY-App-2024-03#46]
Beim löschen von Alarmen gibt es keine Bestätigungsanfrage und man kann überall auf den Alarm klicken, um diesen zu löschen
--Verbesserungsvorschläge--> eine bestätigugsanfrage zum löschen erstellen + das Icon mit einem Iconbutton ersetzen...

**Comment by stauseepokal** [comment]
Idea: Click on the Button -> Menu Opens that asks you if you are sure to delete or want to edit it
