### ISSUE TITLE
Overflow on Alarm

### ISSUE THREAD

**Issue by ajfdik** [BogyMitutoyoCTL/BOGY-App-2024-03#49]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/158302750/47549322-ba27-413c-9a16-f0e986675121)

wenn man ein gerät mit einem 1inch Bildschirm erstellt, dann gibt es einen Overflow bei der Seite von den Alarmen

**Comment by thomasw-mitutoyo-ctl** [comment]
Seems fixed. I have created a 1" device and I didn't get an overflow.
