### ISSUE TITLE
Implement Alarms dialog

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2024-03#5]
![grafik](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/25632350/89505b52-ce2e-4830-b609-4df4f60eb1c2)

**Comment by stauseepokal** [comment]
Add an Select Menu for:
- Temp Value
- Alarm type (low, high)
...in the Modal

**Comment by stauseepokal** [comment]
Finished
[Update_Alarm_managing.webm](https://github.com/BogyMitutoyoCTL/BOGY-App-2024-03/assets/140964926/e52b18aa-d08e-491a-945c-dbd19817a03f)
