### ISSUE TITLE
Theme_Settings Dialog erstellen

### ISSUE THREAD

**Issue by ajfdik** [BogyMitutoyoCTL/BOGY-App-2024-03#9]
Den Dialog für die Theme Settings erstellen

**Comment by ajfdik** [comment]
Das switchen zwischen verschiedenen Themes funktioniert in der Theorie, jedoch können Themes bisher nur beim Start geändert werden, dabei werden Einstellungen jedoch nicht übernommen

**Comment by thomasw-mitutoyo-ctl** [comment]
Fixed with commit 5e99aa14c6988ef4f5a729bbf3ecf4f588d290fd
